#!/bin/bash

echo "Entrez un  mot: " #On affiche à l'écran le texte indiqué qui invite l'utilisateur à entrer un mot
read word #On récupère le mot entré par l'utilisateur
curl http://www.viedemerde.fr | grep -w $word |wc -l #Une commande pour compter le nombre de mot "amour" sur la page http://www.viedemerde.fr, ici on compte le nombre de fois où apparait 


